language: java
script: mvn install
jdk:
- oraclejdk7
deploy:
  provider: releases
  api_key:
    secure: F4S7qZdVDNEZ+F3hhoCqe1CD7GJ5YZ87xHhK0naea4lEp/Yvsv+vBx/ZlNAHtVdyPCaVl7sam5UyOFUtAaRQPsYp9RKZoOl7GlehyYnPbiGusNhdon0IeGMf/6cPeFKFH0JfVcJqrDvu1NdAqNcTnwMDiD0JjDuZAi28opVPM6w=
  file: /home/travis/build/DeckerCHAN/ModTranslator/target/ModTranslator.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: DeckerCHAN/ModTranslator
